apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx-frontend
  name: nginx-only
  namespace: dervish
spec:
  selector:
    matchLabels:
      app: my-front
  replicas: 1
  template:
    metadata:
      labels:
        app: my-front
    spec:
      containers:
        - name: nginx-app
          image: nginx:1.27