apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  selector:
    matchLabels:
      app: nmlt
  replicas: 3
  template:
    metadata:
      labels:
        app: nmlt
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.4
        ports:
        - containerPort: 80
      initContainers:
      - name: init-mysvc
        image: busybox:1.37
        command: ['sh', '-c', "until nslookup mysvc.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mysvc; sleep 2; done"]
      - name: init-mydb
        image: busybox:1.37
        command: ['sh', '-c', "until nslookup mydb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done"]